# промышленный протокинетический резак
- type: entity
  parent: BaseItem
  id: WeaponProtoKineticCutterIndustrial
  name: промышленный протокинетический резак
  suffix: LavaLand
  description: Стреляет сконцентрированным кинетическим зарядом. Вместо разных снарядов стреляет одним комплексным, который обладает свойствами как бурового, так и боевого.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
    layers:
    - state: icon
      map: ["enum.GunVisualLayers.Base"]
  - type: Clothing
    slots:
    - suitStorage
    sprite: _Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
  - type: Item
    size: Large
    sprite: _Adventure/Roles/LavaLand/Equipment/industrial_kinetic_cutter.rsi
  - type: Gun
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    fireRate: 0.5
    angleDecay: 45
    minAngle: 44
    maxAngle: 45
    soundGunshot:
      path: /Audio/_Adventure/LavaLand/cutter_shot.ogg
      params:
        volume: 8
    soundEmpty:
      path: /Audio/Effects/box_deploy.ogg
  - type: GunRequiresWield
  - type: Wieldable
    unwieldOnUse: false
  - type: GunWieldBonus
    minAngle: -43
    maxAngle: -43
  - type: AmmoCounter
  - type: Appearance
  - type: ClothingSpeedModifier
    walkModifier: 0.90
    sprintModifier: 0.90
  - type: HeldSpeedModifier
  - type: UseDelay
    delay: 0.5
  - type: Battery
    maxCharge: 200
    startingCharge: 200
    pricePerJoule: 0.3
  - type: BatteryAmmoProvider
    proto: Advanced-BulletProtoCutter
    fireCost: 20
  - type: BatterySelfRecharger
    autoRechargeRate: 8
    autoRecharge: true

- type: entity
  id: Advanced-BulletProtoCutter
  name: кинетический заряд
  parent: BaseBullet
  categories: [ HideSpawnMenu ]
  components:
  - type: Reflective
    reflective:
      - NonEnergy
  - type: Sprite
    noRot: false
    sprite: _Adventure/Roles/LavaLand/Equipment/bullet.rsi
    state: bullet
    shader: unshaded
    color: "#9c3167"
  - type: GatheringProjectile
    amount: 30
  - type: Projectile
    deleteOnCollide: false
    damage:
      types:
        Blunt: 25
        Piercing: 10
        Structural: 65
  - type: StaminaDamageOnCollide
    damage: 10
  - type: TimedDespawn
    lifetime: 0.2
  - type: PointLight
    color: "#d31e45b8"
    energy: 4
    radius: 1.7
    softness: 1
    enabled: true
  - type: Fixtures
    fixtures:
      projectile:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.075,-0.075,0.075,0.075"
        hard: false
        mask:
        - Opaque
  - type: Ammo
    muzzleFlash: null
