#Смола улья
- type: entity
  id: AlianWeb
  suffix: Чужой
  name: смола
  description: Смола, вырабатываемая ксеноморфами для постройки улья.
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
    - type: DamageContacts # COTULa's, усилил в 2 раза
      damage:
        groups:
          Brute: -1
          Burn: -1
          Airloss: -1
          Toxin: -1
          Genetic: -1
      ignoreWhitelist:
        tags:
        - CanPilot
        - CannotSuicide
        - VimPilot
    - type: MeleeSound
      soundGroups:
        Brute:
          path:
            "/Audio/Weapons/slash.ogg"
    - type: Sprite
      sprite: _Adventure/Roles/Alian/alian_web.rsi
      layers:
        - state: Alian_web0
          map: ["spiderWebLayer"]
      drawdepth: FloorTiles
    - type: Appearance
    - type: RandomSprite
      available:
      - 0:
          Alian_web0: ""
      - 0:
          Alian_web1: ""
      - 0:
          Alian_web2: ""
      - 0:
          Alian_web3: ""
      - 0:
          Alian_web4: ""
      - 0:
          Alian_web5: ""
      - 0:
          Alian_web6: ""
      - 0:
          Alian_web7: ""
    - type: Clickable
    - type: Transform
      anchored: true
    - type: Physics
    - type: Fixtures
      fixtures:
        fix1:
          hard: false
          density: 7
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5,-0.5,0.5,0.5"
          layer:
          - MidImpassable
    - type: Damageable
      damageModifierSet: Alien
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 30
        behaviors:
        - !type:DoActsBehavior
          acts: [ "Destruction" ]
    - type: Temperature
      heatDamage:
        types:
          Heat: 10
      coldDamage: {}
      ColdDamageThreshold: 0
    - type: Flammable
      fireSpread: true
      cold:
        types: {}
      damage:
        types:
          Heat: 10
    - type: Reactive
      groups:
        Flammable: [Touch]
        Extinguish: [Touch]
    - type: SpiderWebObject
    - type: SpeedModifierContacts
      walkSpeedModifier: 0.5
      sprintSpeedModifier: 0.5
      ignoreWhitelist:
        tags:
        - AlienXeno
    - type: EmitSoundOnSpawn
      sound:
        path: /Audio/_Adventure/Voice/alian/alien_slime_spawn.ogg
        params:
          volume: -5
    - type: AtmosDevice
    - type: GasMiner
      maxExternalPressure: 105
      spawnAmount: 0.1
      spawnGas: Ammonia

#Стена
- type: entity
  parent: BaseWall
  id: AlianWall
  suffix: Чужой
  name: смолянная стена
  description: Довольно крепкое сооружение ксеноморфов из слизи.
  components:
  - type: Damageable
    damageModifierSet: Aliens
  - type: IconSmooth
    key: walls
    base: Alian
  - type: Sprite
    sprite: _Adventure/Roles/Alian/alian_Wall.rsi
    layers:
    - state: Alian_wall
  - type: Icon
    sprite: _Adventure/Roles/Alian/alian_Wall.rsi
    state: Alian_wall
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600 # COTULa's, на 50% больше
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: AliensWallDestroy

#Спавн Стены
- type: entity
  parent: WallSpawnAsteroid
  id: AlianWallSpawn
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Adventure/Roles/Alian/alian_Wall.rsi
    layers:
    - state: Alian_wall_Spawn
  - type: SpawnOnDespawn
    prototype: AlianWall
  - type: TimedDespawn
    lifetime: 1.4 # Было 0.7
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/_Adventure/Voice/alian/alien_slime_spawn.ogg
      params:
        volume: -5

#Дверь
- type: entity
  id: AlienDoor
  parent: BaseStructure
  name: смолянной проход
  suffix: Чужой
  description: Никто не знает, что вас ждёт за этим проходом.
  placement:
    mode: SnapgridCenter
  components:
  - type: Tag
    tags:
      - EmagImmune
      - Structure
  - type: InteractionOutline
  - type: Sprite
    sprite: _Adventure/Roles/Alian/alian_door.rsi
    layers:
    - state: closed
      map: ["enum.DoorVisualLayers.Base"]
    - state: closed_unlit
      map: ["enum.DoorVisualLayers.BaseUnlit"]
    - state: welded
      map: ["enum.WeldableLayers.BaseWelded"]
    - state: bolted_unlit
      map: ["enum.DoorVisualLayers.BaseBolted"]
    - state: emergency_unlit
      map: ["enum.DoorVisualLayers.BaseEmergencyAccess"]
    - state: panel_open
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
  - type: AnimationPlayer
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        density: 100
        mask:
        - FullTileMask
        layer:
        - WallLayer
  - type: DoorBolt
  - type: Door
    closeTimeTwo: 0.4
    openTimeTwo: 0.4
    crushDamage:
      types:
        Blunt: 50
    openSound:
      path: /Audio/_Adventure/Voice/alian/aliendoor_opening.ogg
    closeSound:
      path: /Audio/_Adventure/Voice/alian/aliendoor_closing.ogg
    denySound:
      path: /Audio/_Adventure/Voice/alian/alien_slime_spawn.ogg
  - type: Airlock
    openUnlitVisible: true
  - type: NavMapDoor
  - type: AccessReader
    access: [["AlienAccess"]]
  - type: Appearance
  - type: WiresVisuals
  - type: ApcPowerReceiver
    powerLoad: 0
  - type: ExtensionCableReceiver
  - type: Electrified
    enabled: false
    usesApcPower: true
  - type: Airtight
  - type: Occluder
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Aliens
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600 # COTULa's, на 50% больше
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:PlaySoundBehavior
        sound:
          collection: AliensWallDestroy

#Спавн двери
- type: entity
  parent: WallSpawnAsteroid
  categories: [ HideSpawnMenu ]
  id: AlienDoorSpawn
  components:
  - type: Sprite
    sprite: _Adventure/Roles/Alian/alian_door.rsi
    layers:
    - state: Alien_Door_Spawn
  - type: SpawnOnDespawn
    prototype: AlienDoor
  - type: TimedDespawn
    lifetime: 1.4 # Было 0.7
  - type: EmitSoundOnSpawn
    sound:
      path: /Audio/_Adventure/Voice/alian/alien_slime_spawn.ogg
      params:
        volume: -5